# Generated by Django 3.0.8 on 2020-12-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OerData',
            fields=[
                ('oer_auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('oer_auto_date', models.DateTimeField(auto_now=True, verbose_name='Kayıt Tarihi ve Saati')),
                ('oer_title', models.CharField(max_length=500, verbose_name='Başlık')),
                ('oer_subject', models.CharField(max_length=1000, verbose_name='Konu')),
                ('oer_description', models.TextField(verbose_name='Özet')),
                ('oer_type', models.CharField(max_length=500, verbose_name='Kaynak Tipi')),
                ('oer_creator', models.CharField(max_length=500, verbose_name='Yaratıcı')),
                ('oer_publisher', models.CharField(blank=True, max_length=500, null=True, verbose_name='Yayıncı')),
                ('oer_contributor', models.CharField(blank=True, max_length=500, null=True, verbose_name='Katkı Sağlayan')),
                ('oer_license', models.CharField(max_length=100, verbose_name='Açık Lisans')),
                ('oer_date', models.DateField(blank=True, null=True, verbose_name='Tarih')),
                ('oer_language', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dil')),
                ('oer_format', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dosya Biçimi')),
                ('oer_identifier', models.CharField(max_length=500, verbose_name='Tanımlayıcı Adres (URL)')),
                ('oer_educationalAudience', models.CharField(blank=True, max_length=500, null=True, verbose_name='Hedef Kitle')),
                ('oer_educationalUse', models.CharField(blank=True, max_length=500, null=True, verbose_name='Eğitsel Kullanım')),
                ('oer_accessibilityFeature', models.CharField(blank=True, max_length=100, null=True, verbose_name='Erişilebilirlik Özellikleri')),
                ('oer_timeRequired', models.IntegerField(blank=True, null=True, verbose_name='İhtiyaç Duyulan Süre')),
            ],
        ),
    ]
