# Generated by Django 3.1 on 2020-12-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20201222_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeData',
            fields=[
                ('type_auto_id', models.AutoField(primary_key=True, serialize=False, verbose_name='OER ID')),
                ('type_auto_date', models.DateTimeField(auto_now=True, verbose_name='Kayıt Tarihi ve Saati')),
                ('type_name', models.CharField(max_length=50, verbose_name='Ad')),
            ],
        ),
        migrations.AlterField(
            model_name='oerdata',
            name='oer_auto_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='OER ID'),
        ),
    ]
