# Generated by Django 3.0.8 on 2020-12-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='oersTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oer_name', models.CharField(max_length=200)),
                ('oer_url', models.CharField(max_length=200)),
            ],
        ),
    ]
