# Generated by Django 3.0.8 on 2020-12-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oerstest',
            name='oer_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Kayıt Tarihi ve Saati'),
        ),
    ]
