# Generated by Django 3.0.8 on 2020-12-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oers', '0003_oer_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oer_data',
            name='oer_publisher',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Yayıncı'),
        ),
    ]
