# Generated by Django 3.0.8 on 2020-12-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oers', '0004_auto_20201213_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oer_data',
            name='oer_accesibilityFeature',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Erişilebilirlik Özellikleri'),
        ),
        migrations.AlterField(
            model_name='oer_data',
            name='oer_contributer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Katkı Sağlayan'),
        ),
        migrations.AlterField(
            model_name='oer_data',
            name='oer_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='oer_data',
            name='oer_educationalAudience',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Hedef Kitle'),
        ),
        migrations.AlterField(
            model_name='oer_data',
            name='oer_educationalUse',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Eğitsel Kullanım'),
        ),
        migrations.AlterField(
            model_name='oer_data',
            name='oer_format',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dosya Biçimi'),
        ),
        migrations.AlterField(
            model_name='oer_data',
            name='oer_language',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dil'),
        ),
        migrations.AlterField(
            model_name='oer_data',
            name='oer_timeRequired',
            field=models.IntegerField(blank=True, null=True, verbose_name='İhtiyaç Duyulan Süre'),
        ),
    ]
