# Generated by Django 3.0.8 on 2020-12-13 01:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oers', '0005_auto_20201213_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oerstest',
            name='oer_date',
        ),
        migrations.AddField(
            model_name='oerstest',
            name='oer_types',
            field=models.CharField(choices=[('Etkileşimli Kaynak', 'Etkileşimli Kaynak'), ('Etkinlik', 'Etkinlik'), ('Fiziksel Nesne', 'Fiziksel Nesne'), ('Görsel', 'Görsel'), ('Hareketli Görsel', 'Hareketli Görsel'), ('Hareketsiz Görsel', 'Hareketsiz Görsel'), ('Koleksiyon', 'Koleksiyon'), ('Metin', 'Metin'), ('Servis', 'Servis'), ('Ses', 'Ses'), ('Veri seti', 'Veri seti'), ('Yazılım', 'Yazılım')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
