# Generated by Django 3.0.8 on 2020-12-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oers', '0006_auto_20201213_0418'),
    ]

    operations = [
        migrations.CreateModel(
            name='OerTypeValues',
            fields=[
                ('oer_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('oer_type_name', models.CharField(max_length=100, verbose_name='Başlık')),
            ],
        ),
    ]
